services:
  rocketchat:
    image: rocket.chat:latest
    restart: unless-stopped
    environment:
      - ROOT_URL=http://localhost:3100
      - PORT=3100
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
      - OVERWRITE_SETTING_Show_Setup_Wizard=completed
      - ADMIN_USERNAME=admin
      - ADMIN_PASS=Admin@2026
      - ADMIN_EMAIL=admin@example.com
      - OVERWRITE_SETTING_Accounts_Password_Policy_Enabled=true
      - OVERWRITE_SETTING_Accounts_Password_Policy_MinLength=8
      - OVERWRITE_SETTING_Accounts_Password_Policy_MaxLength=128
      - OVERWRITE_SETTING_Accounts_Password_Policy_ForbidRepeatingCharacters=false
      - OVERWRITE_SETTING_Accounts_Password_Policy_ForbidRepeatingCharactersCount=3
      - OVERWRITE_SETTING_Accounts_Password_Policy_AtLeastOneLowercase=true
      - OVERWRITE_SETTING_Accounts_Password_Policy_AtLeastOneUppercase=true
      - OVERWRITE_SETTING_Accounts_Password_Policy_AtLeastOneNumber=true
      - OVERWRITE_SETTING_Accounts_Password_Policy_AtLeastOneSpecialCharacter=true
      - OVERWRITE_SETTING_API_Allow_Infinite_Count=true
      - OVERWRITE_SETTING_Accounts_AllowUserRegistration=true
    ports:
      - "3100:3100"
    depends_on:
      - mongo

  mongo:
    image: mongo:8
    restart: unless-stopped
    command: mongod --oplogSize 128 --replSet rs0
    volumes:
      - mongo_data:/data/db

  mongo-init-replica:
    image: mongo:8
    command: >
      bash -c "sleep 10 && mongosh --host mongo --eval 'rs.initiate({ _id: \"rs0\", members: [{ _id: 0, host: \"mongo:27017\" }] })'"
    depends_on:
      - mongo

volumes:
  mongo_data:
